version: '2'
services:
  api-todo-list:
    tty: true
    build: .
    volumes:
      - "./api:/src/api"
    ports:
      - "3000:3000"
    links:
      - "db-todo-list-test:mongo"
    entrypoint:
      - "npm"
      - "run"
      - "test-watch"
    environment:
      - "NODE_CONFIG_DIR=./api/config"
  db-todo-list-test:
    tty: true
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "data-db-todo-list-test:/data/db"
volumes:
  data-db-todo-list-test:
    driver: local
