version: '2'
services:
  api-todo-list:
    tty: true
    build: .
    volumes:
      - "./api:/src/api"
    ports:
      - "3000:3000"
      - "5858:5858"
      - "8080:8080"
    links:
      - "db-todo-list:mongo"
    entrypoint:
      - "npm"
      - "run"
      - "remote:debug"
    environment:
      - "NODE_CONFIG_DIR=./api/config"
  db-todo-list:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "data-db-todo-list:/data/db"
volumes:
  data-db-todo-list:
    driver: local
