env:
  es6: true
  node: true
  mocha: true
plugins: ["node"]
extends: ["eslint:recommended", "plugin:node/recommended"]
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - error
    - allow: ["warn", "error"]
  node/no-missing-require:
    - 0
  node/no-unpublished-require:
    - 0
